- docker/px4-dev/DockerfileSnapdragon
Since the Intrinsyc qrlSDK has been removed anyway, and to save space,
let's just use the trusty sysroot.
> Snapdragon: Don't use the qrlSDK

- docker/px4-dev/DockerfileSnapdragon
Using -trim will substantially reduce the size of the SDK and Hexagon Tools install.
Signed-off-by: Mark Charlebois <charlebm@gmail.com>
> Added -trim option to installv3.sh for Snapdragon container

- docker/px4-dev/DockerfileSnapdragon
Replaces #28.
The current docker image is built with https://github.com/ATLFlight/cross_toolchain/pull/8.
> Snapdragon: purge some more files

- docker/px4-dev/DockerfileRPi
This PR adds a docker file for the RPi and Parrot Bebop toolchains for Circle CI. Originally, this came up in PX4/Firmware#5504.
I tested it locally and the posix_rpi_cross and posix_bebop_default targets compiled without errors. However, I have one question: the script `./install_cross.sh` in line 45 has a few commands with sudo. When building the docker image, this didn't work, which is why I switch to the root user before that call. I am not sure about the solution and want to ask if there is a better way to do this?
> Add docker file for RPi and Parrot Bebop toolchains

- docker/px4-dev/DockerfileSnapdragon
These changes are needed for some upstream ATLFlight updates.
See: https://github.com/ATLFlight/cmake_hexagon/pull/10 and https://github.com/PX4/Firmware/pull/5552.
@dagar: I've pushed a new image to `julianoes/px4-snappy-2016-10-16`.
> Update Snappy Dockerfile

- docker/px4-dev/Dockerfile_base
- docker/px4-dev/Dockerfile_simulation
@jgoppert I think this is what you actually need?
The images are a hierarchy with px4-dev-base containing all the core PX4 dependencies, but only able to build posix_sitl_default. We try to keep base and nuttx as small as possible because the CI systems pull them every single build.
base
--nuttx
----simulation
------ROS
Once this makes it to docker hub (~20 minutes after merging) you'll need to update the image the build system uses here - https://github.com/PX4/Firmware/blob/master/Tools/docker_run.sh#L15
If you just drop the date (the tag) it'll default to the latest. https://hub.docker.com/r/px4io/px4-dev-nuttx/builds/
> move jinja to px4-dev-base for param generation

- docker/px4-dev/Dockerfile_nuttx_clang
Adds Docker for https://github.com/PX4/Firmware/pull/6552, https://github.com/PX4/Firmware/pull/6892.
It seems that multiple `FROM` is a sour topic so I'd be happy to change it depending on the feedback.
> Docker File for NuttX + Clang Build.

- docker/px4-dev/Dockerfile_simulation
So I have added env var SVGA_VGPU10=0 in order to disable OpenGL 3.3 for the container 
Source of the fix http://answers.gazebosim.org/question/13214/virtual-machine-not-launching-gazebo/
> Fix Gazebo crash in VMWare Fusion with OpenGL 3.3 support

- docker/px4-dev/Dockerfile_base
Fast-RTPS requires openjdk-8 to run.
Signed-off-by: Mark Charlebois <charlebm@gmail.com>
> Added Fast-RTPS support into base image

- docker/px4-dev/Dockerfile_nuttx
@davids5 FYI adding nuttx tools to px4-dev-nuttx. Primarily used in the builds, but can also be used locally quite easily.
Newer NuttX is running `make olddefconfig` at the end of configure.sh. https://bitbucket.org/nuttx/nuttx/src/cc1f7a63fa4180c3effb951f0b2f7d8df89e1fd3/tools/configure.sh?at=master&fileviewer=file-view-default#configure.sh-302
This should also make it slightly easier for people wanting to work on nuttx itself.
> px4-dev-nuttx build nuttx tools

- docker/px4-dev/Dockerfile_armhf
Adds dockerfile with toolchains to build posix_ocpoc_ubuntu target. I'm in the process of adding ocpoc to CI in response to [Firmware PR #7787](https://github.com/PX4/Firmware/pull/7787).
Note I am brand new to docker and containers, so I apologize in advance if I've missed anything major. This seems too simple to necessitate an entirely separate image, but I didn't want to step on anything else. I've been able to build a local 'px4io/px4-dev-ocpoc' and use it with the 'Firmware/Tools/docker_run.sh' script to run a test build of posix_ocpoc_ubuntu. However, I'll probably need a bit of help getting an image into the docker hub.
> Add dockerfile for ocpoc_zynq

- docker/px4-dev/Dockerfile_base
Needed by https://github.com/PX4/Firmware/pull/8063
> px4_dev base: add python-numpy and python-toml

- docker/px4-dev/Dockerfile_armhf
- docker/px4-dev/Dockerfile_base
- docker/px4-dev/Dockerfile_clang
- docker/px4-dev/Dockerfile_nuttx
- docker/px4-dev/Dockerfile_raspi
@dagar `px4io/px4-dev-base` was correctly rebuilt with tag `jlecoeur`.
But other images were not built with that tag as they were not changed: they still source `px4io/px4-dev-base` and do not contain numpy and toml.
I modified all px4 images to source `px4io/px4-dev-base:pr-jlecoeur`, this way I will be able to modify `.travis.yml` and `docker_run.sh` on PX4 side to pass tests on https://github.com/PX4/Firmware/pull/8063.
While it should work, it's kind of convoluted, I hope there is a better way. The last commit will have to reverted before merging.
> px4_dev base: add python-numpy and python-toml (bis)

- docker/px4-dev/Dockerfile_base_archlinux
- docker/px4-dev/scripts/archlinux_install_script.sh
The build on newer gcc versions is broken. Here is an Arch image with gcc7 and arm-none-eabi-gcc7 installed. 
I suggest to run CI on this image for posix_sitl_default, px4fmu-v2_default and px4fmu-v5_default.
@dagar
> Add Arch Linux image to run tests with gcc7 and arm-none-eabi-gcc7

- docker/px4-dev/Dockerfile_ros
pymavlink package is used to create the mavlink message for simulating GCS heartbeat.
It is used here --> https://github.com/PX4/Firmware/blob/d3b4cd3c8ffbc956a737b5344a1841885a0d1eec/integrationtests/python_src/px4_it/mavros/mission_test.py#L55
> add ROS tests dependency

- docker/px4-dev/Dockerfile_simulation
Based on @LorenzMeier comment (https://github.com/PX4/sitl_gazebo/pull/136#pullrequestreview-86030313), we should have mavlink headers that are independent from the ROS framework.
> add mavlink headers

- docker/px4-dev/Dockerfile_simulation
- user built headers normally go to /usr/local/include
- I believe only mavlink v2.0 is needed
> px4-dev-simulation update mavlink location

- docker/px4-dev/Dockerfile_ros
We are missing `catkin tools` to be able to build packages using a better `catkin build` instead of `catkin_make`.
@dagar can you bring this in and tag the container? Thanks!
> px4-dev-ros: add catkin-tools install

- docker/px4-dev/Dockerfile_ros
This will force the upgrade of the packages and respective dependencies.
> px4-dev-ros: upgrade python packages installed by pip

- docker/px4-dev/Dockerfile_ros
Add container to run PX4 avoidance.
Enables CI tests for the Firmware avoidance interface (PR on Firmware coming soon)
> avoidance container

- docker/px4-dev/Makefile
Quick fix to `docker/px4-dev/Makefile` to allow `make all` to work.  It otherwise fails because it doesn't know how to build "px4-dev-nuttx-cclang".
> Fix typo in Makefile to allow `make all` to work.

- docker/px4-dev/Dockerfile_base
- docker/px4-dev/scripts/archlinux_install_script.sh
Required for https://github.com/PX4/Firmware/pull/10337
> Dockerfile_base, archlinux_install_script: add pyyaml and cerberus python packages

- docker/px4-dev/Dockerfile_ros-kinetic
In order to fix http://ci.px4.io:8080/blue/organizations/jenkins/PX4%2Fcontainers/detail/master/22/pipeline/144
> px4-dev-ros-kinetic: upgrade to python3 to meet matplotlib requirements

- Jenkinsfile
- docker/px4-dev/Dockerfile_ros2-crystal
This adds a new container which installs the newly released ROS2 Crystal distro. The idea is to deprecate the Ardent container in 1 to 2 months, while the transition is being done. Ardent was officially EOF in December 18, and now Bouncy is also supported in 16.04.
> add ROS2 Crystal container

- docker/px4-dev/Dockerfile_ros2-ardent
- docker/px4-dev/Dockerfile_ros2-bouncy
- docker/px4-dev/Dockerfile_ros2-crystal
Not needed anymore with the changes on the `px4_ros_com` build structure.
> ROS2 containers: remove rmw-opensplice-cpp dependency

- docker/px4-dev/Dockerfile_armhf
- docker/px4-dev/Dockerfile_clang
- docker/px4-dev/Dockerfile_ecl
- docker/px4-dev/Dockerfile_nuttx
- docker/px4-dev/Dockerfile_nuttx_clang
- docker/px4-dev/Dockerfile_raspi
- docker/px4-dev/Dockerfile_ros
- docker/px4-dev/Dockerfile_ros2-bouncy
- docker/px4-dev/Dockerfile_ros2-crystal
- docker/px4-dev/Dockerfile_simulation
It does not make much sense to have the ROS containers independent of the simulation ones, specially when one pretends to use them for testing ROS routines/missions in the simulation environment.
> Base px4-dev-ros from px4-dev-simulation (Ubuntu 18.04)

- docker/px4-dev/Dockerfile_ros2-crystal
Fixes https://github.com/PX4/containers/issues/154, as it is a requirement for building the micro-RTPS bridge in `px4_ros_com`.
> ROS2 Crystal: update Fast-RTPS fastrtpsgen to 1.7.0

- docker/px4-dev/Dockerfile_ros-kinetic
- docker/px4-dev/scripts/entrypoint.sh
With the current container, simulate cameras end up in a boost pointer exception (https://github.com/PX4/Firmware/pull/10780) . 
To run the camera headlessly I can run a xvfb server but it only works with Gazebo8 and not Gazebo7. 
I cannot make xvfb work without sudo inside the container.
> Dockerfile_ros-kinetic: gazebo8, xvfb

- docker/px4-dev/Dockerfile_ros-kinetic
- docker/px4-dev/scripts/entrypoint.sh
If the display isn't specified, such as `-e DISPLAY=:0` detailed in the README, run the virtual X server.
This is required to simulate cameras in SITL tests in Jenkins. Will be needed for https://github.com/PX4/Firmware/pull/10780 and will hopefully address https://github.com/PX4/Firmware/issues/11257 as the FW model has a camera.
Testing details are here https://github.com/PX4/Firmware/pull/10780#issuecomment-458702060.
Supersedes: https://github.com/PX4/containers/pull/166
> entrypoint: Use Xvfb

- docker/px4-dev/Dockerfile_base-xenial
- docker/px4-dev/Dockerfile_ros-kinetic
- docker/px4-dev/Makefile
We need this to update the ros-kinetic container. Solves entrypoint, user and xvfb issues.
I added it to docker hub: https://hub.docker.com/r/px4io/px4-dev-base-xenial
> base: split out a ubuntu 16 version

- docker/px4-dev/Dockerfile_ros-kinetic
this pull request installs matplotlib for python3 which is required for PX4 Firmware pull request [#11412](https://github.com/PX4/Firmware/pull/11412).
> px4-dev-ros-kinetic: add matplotlib dependency for python3

- docker/px4-dev/Dockerfile_base-archlinux
- docker/px4-dev/Dockerfile_base-bionic
This PR bumps Fast-RTPS version to 1.7.2 on Ubuntu 18.04, since it's the default compatible version with ROS 2 Crystal. Besides that, I add the install of this to ArchLinux as well, so anyone using and developing under ArchLinux and wanting to use these containers also is able to use Fast-RTPS.
@julianoes can I have your review on the ArchLinux side? Thanks!
> Fast-RTPS: bump to 1.7.2 and add to ArchLinux

- docker/px4-dev/Dockerfile_ros2-ardent
- docker/px4-dev/Dockerfile_ros2-bouncy
- docker/px4-dev/Dockerfile_ros2-crystal
`px4_ros_com` requires [`genmsg`](http://wiki.ros.org/genmsg) and [`gencpp`](http://wiki.ros.org/gencpp) to generate the required micro-RTPS agent headers and source code. These are both, by default, included in the ROS1 distributions, but not in ROS2.
As `px4_ros_com` is a ROS2 package and we require the aforementioned packages, these need to be installed first in the Python3 path (which is the one used by the ROS2 environment). This allows using `px4_ros_com` standalone without the need of sourcing ROS1 environments (reported in https://github.com/PX4/px4_ros_com/issues/24).
Since `python3-genmsg` and `python3-gencpp` are only available in Ubuntu 18.10 and above, one needs to download from the source mirrors and install the deb package manually instead of using `apt`.
> ROS2 containers: install python3-genmsg and python3-gencpp from deb sources

- docker/px4-dev/Dockerfile_ros-kinetic
- docker/px4-dev/Dockerfile_ros-melodic
We added matplotlib here: https://github.com/PX4/containers/pull/86
It is used by px4tools. px4tools manages it's own dependencies here: https://github.com/dronecrew/px4tools/blob/master/setup.py
Version 2.2.x is LTS for python2 and 2.2.4 (current newest) is what is installed from px4tools. Then later in the build, it is upgraded to 3.1, which is not compatible. 
See the blurb on the right at https://matplotlib.org/
```
Matplotlib 3.0 is Python 3 only.
For Python 2 support, Matplotlib 2.2.x will be continued as a LTS release and updated with bugfixes until January 1, 2020.
```
Also,
```
Beginning with Matplotlib 3.1, Python 3.6 or above is required.
```
In the build:
```
Collecting matplotlib>=2.2.2 (from px4tools)
Downloading https://files.pythonhosted.org/packages/32/6b/0368cfa5e1d1ae169 …
```
> Fix matplotlib dependency

- docker/px4-dev/Dockerfile_base-bionic
- docker/px4-dev/Dockerfile_base-xenial
- docker/px4-dev/Dockerfile_ros2-bouncy
This PR matches the releases of Fast-RTPS with the respective used version in ROS2. By default, we are keeping Fast-RTPS 1.7.2 as the stable Fast-RTPS version, as it is supported in both ROS 2 Crystal (the currently supported released for `px4_ros_com`) and Dashing (LTS, but pending support in `px4_ros_com`).
> Fast-RTPS: sync version for each ROS2 release

- docker/README.md
px4-dev-simulation-**bouncy** -> px4-dev-simulation-**bionic**
> docker: fix README typo

- Jenkinsfile
- docker/Dockerfile_base-archlinux
- docker/Dockerfile_base-bionic
- docker/Dockerfile_ros-melodic
- docker/Dockerfile_ros2-ardent
- docker/Dockerfile_ros2-bouncy
- docker/Dockerfile_ros2-crystal
- docker/Dockerfile_ros2-dashing
- docker/Dockerfile_ros2-eloquent
- docker/Makefile
- docker/README.md
Alpha release already happen. Roadmap under https://index.ros.org//doc/ros2/Releases/Release-Eloquent-Elusor/#id6.
> docker: add ROS2 Eloquent container | update ROS2 containers dependencies

- docker/Dockerfile_base-archlinux
- docker/Dockerfile_base-bionic
- docker/Dockerfile_base-xenial
- docker/Dockerfile_ros-kinetic
- docker/Dockerfile_ros-melodic
- docker/Dockerfile_simulation-bionic
- docker/Dockerfile_simulation-xenial
This goes with https://github.com/PX4/Firmware/pull/12809.
> px4-dev: Try to move to Python 3

- docker/Dockerfile_simulation-bionic
This is required for testing using MAVSDK in https://github.com/PX4/Firmware/pull/13075.
> docker: add MAVSDK library to simulation-bionic

- docker/Dockerfile_ros-kinetic
- docker/Dockerfile_ros-melodic
As per https://github.com/PX4/sitl_gazebo/pull/373, we also need *catkin_pkg* installed in the Python 3 path, in order to build catkin packages.
> Install catkin_pkg by pip3

- docker/Dockerfile_base-archlinux
- docker/Dockerfile_base-bionic
- docker/Dockerfile_base-xenial
- docker/Dockerfile_ros2-ardent
- docker/Dockerfile_ros2-bouncy
- docker/Dockerfile_ros2-crystal
- docker/Dockerfile_ros2-dashing
- docker/Dockerfile_ros2-eloquent
https://github.com/PX4/Firmware/pull/13572 removes `genmsg` and `gencpp` submodules. Since `gencpp` is not used, `genmsg` needs to be installed on the containers. https://pypi.org/project/pyros-genmsg/ provides the `genmsg` python package, required to generate the source code for uORB topics and the micro-RTPS bridge.
> install pyros-genmsg with pip3 (equivalent to python3-genmsg) on base containers

- docker/Dockerfile_nuttx
This change, which eventually should be made again as soon as https://github.com/PX4/Firmware/pull/13448 is considered definite and complete, is blocking other unrelated PR's which require updated container tags (like https://github.com/PX4/Firmware/pull/13572).
> px4-dev-nuttx: revert GNU Arm toolchain update to version 7

- docker/Dockerfile_ros-kinetic
- docker/Dockerfile_ros-melodic
This PR adds dependencies for the [PX4/avoidance](https://github.com/PX4/avoidance) to enable SITL testing on Jenkins.
I am not sure if making the `px4io/px4-dev-ros-melodic` image larger will be a better decision instead of creating a docker image just for the avoidance testing.
> Add avoidance dependencies for testing

- docker/Dockerfile_armhf
- docker/Dockerfile_base-archlinux
- docker/Dockerfile_base-bionic
- docker/Dockerfile_base-xenial
- docker/Dockerfile_clang
- docker/Dockerfile_nuttx
- docker/Dockerfile_nuttx_clang
- docker/Dockerfile_raspi
- docker/Dockerfile_ros-kinetic
- docker/Dockerfile_ros-melodic
- docker/Dockerfile_ros2-ardent
- docker/Dockerfile_ros2-bouncy
- docker/Dockerfile_ros2-crystal
- docker/Dockerfile_ros2-dashing
- docker/Dockerfile_ros2-eloquent
- docker/Dockerfile_simulation-bionic
- docker/Dockerfile_simulation-xenial
This removes custom install pip install and upgrade commands. Instead we should be relying on what the package manager (mostly apt-get) provides.
Generally, the packages are made so that pip works for Python 2 and pip3 works for Python 3.
Additionally, all date tags are updated so that we can rebuild all the images.
> docker: use pip installed by package manager

- docker/Dockerfile_base-archlinux
- docker/Dockerfile_simulation-bionic
- docker/Dockerfile_simulation-xenial
When running SITL we need to call bc in the startup script for floating point calculations.
Related to https://github.com/PX4/Firmware/pull/13867.
> docker: SITL needs bc

- docker/Dockerfile_ros-kinetic
- docker/Dockerfile_ros-melodic
This needs to be added since it's no longer in the base containers.
> docker: pip2 missing for ROS containers

- docker/Dockerfile_ros-kinetic
- docker/Dockerfile_ros-melodic
This should not be needed at all, hopefully.
I'm hoping that this way we don't run into troubles installing px4tools which in turn tries to install matplotlib which does not install with our old pip version.
> docker: Don't install pip2

- docker/Dockerfile_ros-kinetic
- docker/Dockerfile_ros-melodic
To fix PX4 Firmware ROS tests.
> ROS containers: add python-rospkg

- docker/Dockerfile_ros-kinetic
- docker/Dockerfile_ros-melodic
Required for a `catkin` build (http://ci.px4.io:8080/blue/organizations/jenkins/PX4%2FFirmware/detail/PR-13572/34/pipeline/25).
> ROS containers: add python-jinja2

- .github/workflows/docker_builds.yml
> workflows: armhf no longer depends on Ubuntu base

- docker/Dockerfile_simulation-bionic
We don't need this as we can easily install it later and therefore move the mavsdk version specification to the Firmware repository.
This is not urgent as we can already replace the installed version in the PX4/Firmware tests.
> docker: remove MAVSDK install

- docker/Dockerfile_ros2-ardent
- docker/Dockerfile_ros2-bouncy
> docker: remove ros2bag

- docker/Dockerfile_nuttx
This is again blocking the update of containers in upstream PX4 (https://github.com/PX4/Firmware/pull/14401). @dagar 2020-02-13 tag should contain the version you require to continue.
> revert update for Arm Embedded Toolchain for tag 2020-03-16

- README.md
- docker/Dockerfile_base-focal
- docker/Makefile
Built and tested locally with the `px4_sitl_rtps` target. Runs SITL (with no sim) as expected.
> add px4-dev-base-focal (Ubuntu 20.04)

- docker/Dockerfile_base-bionic
- docker/Dockerfile_base-focal
- docker/Dockerfile_base-xenial
- docker/Dockerfile_ros2-eloquent
*  _px4-dev-base-bionic_:
-  bump Fast-RTPS-Gen to **v1.0.4**;
-  bump Gradle to **6.3-rc4**;
*  _px4-dev-base-focal_:
-  bump Fast-RTPS-Gen to **v1.0.4**;
*  _px4-dev-base-xenial_:
-  install Fast-CDR 1.0.7 from source so the CMake modules to find it are made available;
-  install Fast-RTPS 1.6.0 from source.
Fast-RTPS-Gen v1.0.4 release notes: https://github.com/eProsima/Fast-RTPS-Gen/releases/tag/v1.0.4, being the `-typeros2` option the most relevant to us.
> Fast-RTPS setup: general updates

- docker/Dockerfile_base-xenial
Fixes https://github.com/PX4/containers/runs/813776212?check_suite_focus=true#step:4:1763.
> px4-dev-base-xenial: fix numpy version in 1.18.*

- docker/Dockerfile_nuttx-bionic
- docker/Dockerfile_nuttx-focal
Updates the GNU Arm Embedded Toolchain to version 9-2020-q2-update (released in November 30, 2020) in both Bionic and Focal `nuttx` containers.
> nuttx: update GNU Arm Embedded Toolchain to 9-2020-q2-update

- docker/Dockerfile_ros-noetic
catkin package was broken on Ubuntu focal(ROS noetic)
This was due to the missing dependency, which is added in this PR
from: https://github.com/catkin/catkin_tools/issues/594#issuecomment-651938327
> Fix catkin on ROS noetic

- docker/Dockerfile_simulation-bionic
- docker/Dockerfile_simulation-focal
This installs [jsbsim](https://github.com/JSBSim-Team/jsbsim) in the bionic simulation container.
This will enable build/SITL testing on JSBSim
The deb package is ~2.8MB
> Install jsbsim in simulation container

- docker/Dockerfile_docs
@dagar I'm investigating using Vuepress instead of gitbook for building docs instead of yarn. This adds yarn to the docs environment and will allow me to experiment with the jenkinsfile part of the story. Note, it doesn't clean up gitbook stuff - would not do that until this is all live.
> Add yarn to dockerfile.

- docker/Dockerfile_docs
Yarn isn't being installed (tested from Jenkins). This suggests alternative way of getting it.
> Dockerfile docs: get better source of yarn

- docker/Dockerfile_clang
- docker/Dockerfile_nuttx-bionic
- docker/Dockerfile_nuttx-focal
- docker/Dockerfile_nuttx_clang
- docker/Dockerfile_raspi
- docker/Dockerfile_ros-kinetic
- docker/Dockerfile_ros-melodic
- docker/Dockerfile_ros-noetic
- docker/Dockerfile_ros2-ardent
- docker/Dockerfile_ros2-bouncy
- docker/Dockerfile_ros2-crystal
- docker/Dockerfile_ros2-dashing
- docker/Dockerfile_ros2-eloquent
- docker/Dockerfile_ros2-foxy
- docker/Dockerfile_simulation-bionic
- docker/Dockerfile_simulation-focal
- docker/Dockerfile_simulation-xenial
**Problem Description**
While trying to [add catkin build tests](https://github.com/Auterion/px4-jsbsim-bridge/pull/20) to the PX4/px4-jsbsim-bridge, catkin build tests wouldn't pass since jsbsim wasn't installed inside the container. 
Since JSBSim was added in https://github.com/PX4/containers/pull/276, the base containers of the ROS containers need to be updated
> Update base container for ros melodic/noetic

- docker/Dockerfile_clang
- docker/Dockerfile_nuttx-bionic
- docker/Dockerfile_nuttx-focal
- docker/Dockerfile_nuttx_clang
- docker/Dockerfile_raspi
- docker/Dockerfile_ros-kinetic
- docker/Dockerfile_ros-melodic
- docker/Dockerfile_ros-noetic
- docker/Dockerfile_ros2-ardent
- docker/Dockerfile_ros2-bouncy
- docker/Dockerfile_ros2-crystal
- docker/Dockerfile_ros2-dashing
- docker/Dockerfile_ros2-eloquent
- docker/Dockerfile_ros2-foxy
- docker/Dockerfile_simulation-bionic
- docker/Dockerfile_simulation-focal
- docker/Dockerfile_simulation-xenial
**Problem Description**
This switches the jsbim sim release to a stable release. Previously, it was pointing to a rolling release.
**Additional Context**
- This fixes https://github.com/PX4/PX4-containers/issues/284
- This is the second attempt of https://github.com/PX4/PX4-containers/pull/276
> Include jsbsim v1.1.1 in simulation containers

- docker/Dockerfile_docs
I need this to be able to run web workers (allows speeding up build quite a lot)
> Dockerfile:Docs - add specific nodejs version

- docker/Dockerfile_simulation-bionic
- docker/Dockerfile_simulation-focal
- docker/Dockerfile_simulation-xenial
**Problem Description**
As discussed from the dev call today, this PR removes the mavlink c libraries from the containers
**Additional Context**
This is needed for solving https://github.com/PX4/PX4-Autopilot/pull/16081
> Remove mavlink c library from containers

- docker/Dockerfile_base-archlinux
- docker/Dockerfile_base-xenial
- docker/Dockerfile_clang
- docker/Dockerfile_nuttx-bionic
- docker/Dockerfile_nuttx-focal
- docker/Dockerfile_nuttx_clang
- docker/Dockerfile_raspi
- docker/Dockerfile_ros-kinetic
- docker/Dockerfile_ros-melodic
- docker/Dockerfile_ros-noetic
- docker/Dockerfile_ros2-ardent
- docker/Dockerfile_ros2-bouncy
- docker/Dockerfile_ros2-crystal
- docker/Dockerfile_ros2-dashing
- docker/Dockerfile_ros2-eloquent
- docker/Dockerfile_ros2-foxy
- docker/Dockerfile_simulation-bionic
- docker/Dockerfile_simulation-focal
- docker/Dockerfile_simulation-xenial
1. ArchLinux: Seems to be having problems with `glibc` - https://github.com/PX4/PX4-containers/runs/2111492625?check_suite_focus=true#step:5:389. Upgrading before installing the dependencies now;
2. ROS Melodic: update of pyulog to 0.9.0 breaks (still required) Python 2 compatibility;
3. Trying keeping Xenial alive until Apr 30 2021.
> General fixes

- docker/Dockerfile_base-archlinux
- docker/Dockerfile_ros-kinetic
- docker/Dockerfile_ros-melodic
Hopefully there is a better long run fix for this but it should allow us to fix CI failing.
> ros: freeze python-control==0.8.4 to fix regression

- docker/Dockerfile_docs
Currently failing with bionic: https://github.com/PX4/PX4-containers/runs/3001661210?check_suite_focus=true#step:5:1579. Trying focal. If it doesn't work, then we need to apply a direct fix to the ruby support.
> docs container: use focal as the base container

- docker/Dockerfile_simulation-bionic
- docker/Dockerfile_simulation-focal
**Problem Description**
This PR adds ignition edifice for Ubuntu focal simulation environment
Ignition Edifice is the LTS version for [ignition gazebo](https://ignitionrobotics.org/docs/edifice)
**Additional Context**
- This PR is needed for enabling firmware build tests in https://github.com/Auterion/px4-simulation-ignition/pull/12
> Add ignition edifice for Ubuntu focal simulation environment

- docker/Dockerfile_base-focal
This adds pynacl for signing images
Signed-off-by: Jukka Laitinen <jukkax@ssrc.tii.ae>
> Add pip install pynacl for security enabled targets (signing)

- docker/Dockerfile_armhf
https://github.com/PX4/PX4-Autopilot/pull/21737#pullrequestreview-1489844308
- Update armhf container to Debian 11 bullseye
- Remove Fast-DDS since it's apparently not a dependency anymore
I also tried Debian 12 bookworm and it can be made to work but:
- Raspberry Pi OS is currently on Debian 11. I don't know why this container is Debian based at all but was assuming it's to have less duplication e.g. on a Raspberry Pi.
- Debian 12 enables the python 3 externally managed module protection which is not a concern in the scope of this docker container but `RUN rm /usr/lib/python3.*/EXTERNALLY-MANAGED` needs to be ran before using pip3.
- Fast-DDS doesn't build, has to be updated which added more dependencies which create problems themselves... That's how I got to the idea to remove it since …
> Update armhf container to Debian 11

- .github/workflows/docker_builds.yml
- docker/Dockerfile_simulation-jammy
- docker/Makefile
This adds a simulatio image for ubuntu jammy. Like the `ubuntu.sh` script, it installs Gazebo 7 (Garden).
> Simulation image for Ubuntu Jammy

- docker/Dockerfile_aarch64
- docker/Dockerfile_armhf
- docker/Dockerfile_base-archlinux
- docker/Dockerfile_base-bionic
- docker/Dockerfile_base-focal
- docker/Dockerfile_base-jammy
- docker/Dockerfile_ros-melodic
This fixes the empy version to 3.3.4 (like in https://github.com/PX4/PX4-Autopilot/pull/22466).
This is because empy released 4.x which is incompatible.
> Fix empy version to 3.3.4

- docker/Dockerfile_docs
For vitepress I need Node 18. Might as well update to Jammy too. 
Note, I don't actually "want" to do this - but I can't get github actions to work for deployment to the docs.px4.io.
> Dockerfile docs node18

- docker/Dockerfile_aarch64
- docker/Dockerfile_armhf
- docker/Dockerfile_base-archlinux
- docker/Dockerfile_base-bionic
- docker/Dockerfile_base-focal
- docker/Dockerfile_base-jammy
- docker/Dockerfile_clang
- docker/Dockerfile_nuttx-bionic
- docker/Dockerfile_nuttx-focal
- docker/Dockerfile_nuttx_clang
- docker/Dockerfile_raspi
- docker/Dockerfile_ros-noetic
- docker/Dockerfile_ros2-eloquent
- docker/Dockerfile_ros2-foxy
- docker/Dockerfile_ros2-galactic
- docker/Dockerfile_ros2-rolling
- docker/Dockerfile_simulation-bionic
- docker/Dockerfile_simulation-focal
Overall clean-up and restore of the containers. Details can be found in the commits.
> Overall CI container clean-up

- docker/Dockerfile_aarch64
- docker/Dockerfile_armhf
- docker/Dockerfile_base-bionic
- docker/Dockerfile_base-focal
- docker/Dockerfile_base-jammy
Hello, this pull request adds virtual environment support for the docker builds. This is necessary because newer versions of macos and ubuntu are using python3.12 by default and 3.12 blocks installation of pip dependencies using user level packages and require you to install all libraries using virtual environments. I'm currently working on a PR for this in https://github.com/PX4/PX4-Autopilot/pull/23228, but cannot progress past the CI/CD failures which depend on this package being available.
> add python3-venv so that virtual environment work can be done
