PX4/PX4-containers

docker/ros-indigo/sitl-testing/tools/testing/run-container.bash
docker/ros-indigo/sitl-testing/tools/testing/run-tests.bash

Fixes #7 and will copy rosbags after tests
Waiting on PX4/Firmware/pull/1923

CI updates

---

docker/ros-indigo/px4-ros-full/Dockerfile
docker/ros-indigo/px4-ros-full/scripts/install-python-tools.bash
docker/ros-indigo/sitl-testing/Dockerfile
docker/ros-indigo/sitl-testing/scripts/testing/export_charts.py
docker/ros-indigo/sitl-testing/scripts/testing/run-tests.bash
docker/ros-indigo/sitl-testing/tools/testing/run-container.bash

This adds chart exports for SITL tests :)
@LorenzMeier: I'd add a new repo to PX4 for this: https://github.com/UAVenture/bearcart if that's ok? had to modify it slightly so it can handle sub-second timestamps

Export charts from SITL rosbags

---

docker/ros-indigo/px4-ros-full/Dockerfile
docker/ros-indigo/px4-ros-full/scripts/add-ros-control.bash
docker/ros-indigo/px4-ros-full/scripts/install-python-tools.bash
docker/ros-indigo/px4-ros-full/scripts/install-ros-control.bash
docker/ros-indigo/px4-ros-full/scripts/install-ros.bash
docker/ros-indigo/px4-ros-full/scripts/setup-workspace.bash
docker/ros-indigo/sitl-testing/Dockerfile
docker/ros-indigo/sitl-testing/scripts/testing/export_charts.py
docker/ros-indigo/sitl-testing/scripts/testing/run-tests.bash
docker/ros-indigo/sitl-testing/scripts/testing/setup-workspace.bash
docker/ros-indigo/sitl-testing/tools/testing/run-container.bash

**WIP**
Container update, primarily for PX4/Firmware/issues/1910 (fixing the issue later after wiki update and removal of the old scripts)
Fixes PX4/containers/issues/3

Sync SITL install scripts

---

docker/ros-indigo/px4-ros-full/scripts/install-python-tools.bash
docker/ros-indigo/px4-ros-full/scripts/install-ros-control.bash
docker/ros-indigo/px4-ros-full/scripts/install-ros.bash
docker/ros-indigo/sitl-testing/scripts/testing/run-tests.bash

Switching to shadow repo to get MAVROS binaries sooner.
This will switch the container to latest MAVROS, which will need updates on PX4.

Update to latest MAVROS

---

docker/ros-indigo/px4-ros-full/Dockerfile
docker/ros-indigo/sitl-testing/scripts/testing/export_charts.py

**WIP**
This exports a KML for every test based on local position. 0,0,0 is currently in Schachen Aarau ;). Feel free to suggest a nice plane field somewhere.
There is no frontend yet. I'd like to a add some HTML site per test that includes the KML and the charts before merging.
Fixes PX4/Firmware/issues/1865

KML export for SITL tests

---

docker/px4-dev/Dockerfile
docker/px4-dev/DockerfileRos
docker/px4-dev/scripts/cache-gazebo-models.bash

otherwise they need to be fetched from gazebo servers on each run

added script to cache basic gazebo models in container

---

docker/px4-dev/DockerfileBase

This is my attempt to create the smallest image that can successfully build and test everything that we currently do on travis-ci (make check).

add basic dev image

---

docker/px4-dev/Dockerfile_nuttx_gcc_next

@dagar 
I do not have write access. If this is valid please merge it. If not Please create another DockerFile_nuttx_v3 with this version of the compiler.

Update to 4.9-2015-q3-update

---

docker/px4-dev/DockerfileSnapdragon

Built new image, tested it and pushing it right now.
Related to #30.
FYI @mcharleb

Snapdragon: added ninja-build and ccache

---

docker/px4-dev/Dockerfile_coverity

base + path for coverity tool.
Might expand it to actually include the coverity tooling in the future.

add px4-dev-coverity

---

docker/px4-dev/Dockerfile_simulation

px4-dev-simulation add jinja2

---

docker/px4-dev/Dockerfile_clang

- px4-dev-base with latest clang for running clang-tidy, scan-build

add px4-dev-clang

---

docker/px4-dev/Dockerfile_raspi

Needed before https://github.com/PX4/Firmware/pull/7248 gets merged
Signed-off-by: Nicolae Rosia <nicolae.rosia@gmail.com>

Add toolchain path to PATH

---

docker/px4-dev/Dockerfile_simulation

Use UTF8 encoding in java tools

---

docker/px4-dev/Dockerfile_base
docker/px4-dev/Dockerfile_clang

Merge pr-jlecoeur to master (https://github.com/PX4/containers/pull/77).

px4_dev base: add python-numpy and python-toml

---

docker/px4-dev/scripts/archlinux_install_script.sh

@hamishwillee do you see something else I should add?

Arch: add ccache and ninja, replace git-core by git

---

docker/px4-dev/Dockerfile_ros
docker/px4-dev/Dockerfile_simulation

This is to allow the `mavlink` repo dir to be found by `sitl_gazebo` CI.

px4-dev: dependencies cleanup for ROS and Simulation containers

---

docker/px4-dev/Dockerfile_simulation

https://github.com/PX4/Firmware/issues/10136
@DonLakeFlyer @hamishwillee

px4-dev-simulation add exiftool

---

Jenkinsfile
README.md
docker/px4-dev/Dockerfile_base
docker/px4-dev/Dockerfile_ros
docker/px4-dev/Dockerfile_ros-kinetic
docker/px4-dev/Dockerfile_ros2-ardent
docker/px4-dev/Dockerfile_ros2-bouncy
docker/px4-dev/Dockerfile_simulation
docker/px4-dev/scripts/entrypoint.sh

Solves https://github.com/PX4/containers/issues/138.

Minor ROS1 containers refactor | Add ROS2 containers

---

docker/px4-dev/Dockerfile_base
docker/px4-dev/Dockerfile_simulation

gtest will be used for writing unit test for sitl_gazebo.

Add gtest for writing unit tests

---

Jenkinsfile
docker/px4-dev/Dockerfile_ros
docker/px4-dev/Dockerfile_ros2-ardent
docker/px4-dev/Dockerfile_ros2-bouncy
docker/px4-dev/Dockerfile_simulation

Required as https://hub.docker.com/r/px4io/px4-dev-ros2-bouncy/ is failing to build.

Update ROS/simulation containers tags

---

docker/px4-dev/Dockerfile_armhf
docker/px4-dev/Dockerfile_clang
docker/px4-dev/Dockerfile_docs
docker/px4-dev/Dockerfile_ecl
docker/px4-dev/Dockerfile_nuttx
docker/px4-dev/Dockerfile_nuttx_clang
docker/px4-dev/Dockerfile_raspi
docker/px4-dev/Dockerfile_ros
docker/px4-dev/Dockerfile_ros2-ardent
docker/px4-dev/Dockerfile_ros2-bouncy
docker/px4-dev/Dockerfile_ros2-crystal
docker/px4-dev/Dockerfile_simulation

This is mainly to fix the docs container issues (https://github.com/PX4/containers/pull/168), but a few other containers using entrypoint needed to be fixed and updated.
Side note, but I've lost track of the ROS container hierarchy. Why do the ROS2 images inherit ROS1 melodic?

WIP: containers entrypoint and base cleanup

---

docker/px4-dev/Dockerfile_simulation

Follow up to: https://github.com/PX4/sitl_gazebo/pull/268 and https://github.com/PX4/sitl_gazebo/pull/148

Add good bad and ugly gstreamer plugins to support camera streaming again

---

docker/px4-dev/scripts/entrypoint.sh

entrypoint.sh only start Xvfb if exists

---

docker/px4-dev/Dockerfile_base
docker/px4-dev/Dockerfile_base_archlinux
docker/px4-dev/Dockerfile_clang
docker/px4-dev/Dockerfile_docs
docker/px4-dev/Dockerfile_ecl
docker/px4-dev/Dockerfile_nuttx
docker/px4-dev/Dockerfile_raspi
docker/px4-dev/Dockerfile_ros
docker/px4-dev/Dockerfile_ros-kinetic
docker/px4-dev/Dockerfile_ros2-ardent
docker/px4-dev/Dockerfile_ros2-bouncy
docker/px4-dev/Dockerfile_ros2-crystal
docker/px4-dev/Dockerfile_simulation
docker/ros-indigo/mavros/DockerfileArmhfUbuntu
docker/ros-indigo/mavros/DockerfileRaspbian
docker/ros-indigo/mavros/DockerfileUbuntu
docker/ros-indigo/px4-ros-full/Dockerfile
docker/ros-indigo/sitl-testing/Dockerfile
docker/streaming/gstreamer/DockerfileArmhfUbuntu
docker/streaming/gstreamer/DockerfileRaspbian
docker/streaming/gstreamer/DockerfileUbuntu

- Nothing special here except https://docs.docker.com/engine/reference/builder/#maintainer-deprecated

remove deprecated MAINTAINER and use labels instead

---

docker/px4-dev/README.md

May be just my peeve, but it should help new users.

display is not always :0. Use $DISPLAY instead

---

docker/px4-dev/Dockerfile_ros-kinetic

this pull request installs pip3 and python 3 packages needed for this PX4 Firmware pull request: [#11412](https://github.com/PX4/Firmware/pull/11412)
installation of python 2 packages is maintained to avoid breaking other workflows, but might not be necessary any more.

ros-kinetic: pip3 and python 3 packages for ecl-efk analysis

---

docker/px4-dev/Dockerfile_armhf
docker/px4-dev/Dockerfile_clang
docker/px4-dev/Dockerfile_ecl
docker/px4-dev/Dockerfile_nuttx
docker/px4-dev/Dockerfile_nuttx_clang
docker/px4-dev/Dockerfile_raspi
docker/px4-dev/Dockerfile_ros-kinetic
docker/px4-dev/Dockerfile_ros-melodic
docker/px4-dev/Dockerfile_ros2-ardent
docker/px4-dev/Dockerfile_ros2-bouncy
docker/px4-dev/Dockerfile_ros2-crystal
docker/px4-dev/Dockerfile_simulation

For this to pass CI, I manually built and pushed tags to docker hub. After this passes, I'll merge in and create git tags to match.

update tags to 2019-03-08

---

docker/px4-dev/Dockerfile_ros-kinetic
docker/px4-dev/Dockerfile_ros-melodic
docker/px4-dev/Dockerfile_ros2-ardent
docker/px4-dev/Dockerfile_ros2-bouncy
docker/px4-dev/Dockerfile_ros2-crystal

Details https://discourse.ros.org/t/new-gpg-keys-deployed-for-packages-ros-org/9454

update ROS GPG key  

---

docker/px4-dev/Dockerfile_ros2-bouncy
docker/px4-dev/Dockerfile_ros2-crystal
docker/px4-dev/Dockerfile_ros2-dashing

First LTS release of ROS2, so a good starting point for setting a stable version of the PX4-ROS2 bridge.
Also, updates the other ROS2 parent container tags.

Add ROS2 Dashing container

---

Jenkinsfile
docker/px4-dev/Dockerfile_base-archlinux

Attempt to revive the ArchLinux container.

Revive ArchLinux container

---

Jenkinsfile
docker/px4-dev/Dockerfile_base-archlinux
docker/px4-dev/Dockerfile_base-bionic
docker/px4-dev/Dockerfile_base-xenial
docker/px4-dev/Dockerfile_docs

Also:
1. On CI, sets build target to `px4_sitl_rtps` in the base containers;
2. Installs Fast-RTPS-Gen separately.

Bump Fast-RTPS to 1.8.1

---

docker/ros-indigo/mavros/tools/broadcaster.py
docker/ros-indigo/sitl-testing/scripts/testing/export_charts.py

Python 3 `print()` and some PEP8 warnings.

Fix and minor cleanup for Python3

---

docker/Dockerfile_base-bionic
docker/Dockerfile_base-xenial
docker/Dockerfile_ros2-ardent
docker/Dockerfile_ros2-bouncy
docker/Dockerfile_ros2-crystal
docker/Dockerfile_ros2-dashing
docker/Dockerfile_ros2-eloquent

Looks like we missed installing Python3 in the first place.

Adds python3 and python3-dev

---

docker/Dockerfile_base-bionic
docker/Dockerfile_base-xenial
docker/Dockerfile_ros-kinetic
docker/Dockerfile_ros-melodic
docker/Dockerfile_ros2-ardent
docker/Dockerfile_ros2-bouncy
docker/Dockerfile_ros2-crystal
docker/Dockerfile_ros2-dashing
docker/Dockerfile_ros2-eloquent

Pretends to fix the encoding issues detected in https://github.com/PX4/Firmware/pull/12809 and https://github.com/PX4/Firmware/pull/13572.

Add UTF-8 language encoding

---

docker/Dockerfile_docs

@dagar i *think* this fixes build issues. Can you please test, and if you think OK, then merge. My tests bit broken, but certainly gets further than the old version.

update docs to bionic

---

docker/Dockerfile_simulation-bionic

This version fixes a segfault on init happening every now and then.

docker: update mavsdk

---

docker/Dockerfile_armhf
docker/Dockerfile_clang
docker/Dockerfile_nuttx
docker/Dockerfile_nuttx_clang
docker/Dockerfile_raspi
docker/Dockerfile_ros-kinetic
docker/Dockerfile_ros-melodic
docker/Dockerfile_ros2-ardent
docker/Dockerfile_ros2-bouncy
docker/Dockerfile_ros2-crystal
docker/Dockerfile_ros2-dashing
docker/Dockerfile_ros2-eloquent
docker/Dockerfile_simulation-bionic
docker/Dockerfile_simulation-xenial

I had forgotten to update this.

docker: bump tag to 2020-01-10

---

.github/workflows/docker_builds.yml
README.md
docker/Dockerfile_base-archlinux
docker/Dockerfile_base-bionic
docker/Dockerfile_base-xenial
docker/Dockerfile_nuttx
docker/Dockerfile_ros2-bouncy
docker/Dockerfile_ros2-crystal
docker/Dockerfile_ros2-eloquent

Try to build with more cores, actually push tags, and a badge.

GitHub actions follow up

---

.github/workflows/docker_builds.yml
README.md

- Readme cleanup
- Push latest release to `latest` tag as well.

Fix readme and workflow badge, publish latest as well

---

docker/Dockerfile_base-archlinux
docker/Dockerfile_base-bionic
docker/Dockerfile_base-xenial

Required for Python 2 / 3 compatibility in some places.

docker: add six from PyPi

---

docker/Dockerfile_ros-kinetic
docker/Dockerfile_ros-melodic

No matter what I tried, I could not get catkin to compile Firmware with Python 3.

docker: for ROS we still need Python 2

---

docker/Dockerfile_clang
docker/Dockerfile_nuttx
docker/Dockerfile_nuttx_clang
docker/Dockerfile_raspi
docker/Dockerfile_ros-kinetic
docker/Dockerfile_ros-melodic
docker/Dockerfile_ros2-ardent
docker/Dockerfile_ros2-bouncy
docker/Dockerfile_ros2-crystal
docker/Dockerfile_ros2-dashing
docker/Dockerfile_ros2-eloquent
docker/Dockerfile_simulation-bionic
docker/Dockerfile_simulation-xenial

Hopefully, this panda version should install ok.

Fix pandas python2 install

---

docker/Dockerfile_ros-kinetic

Python 2 is definitely not fun anymore.

docker: fix old version of itertools

---

docker/Dockerfile_base-archlinux
docker/Dockerfile_base-bionic
docker/Dockerfile_base-xenial
docker/Dockerfile_clang
docker/Dockerfile_nuttx
docker/Dockerfile_nuttx_clang
docker/Dockerfile_raspi
docker/Dockerfile_ros-kinetic
docker/Dockerfile_ros-melodic
docker/Dockerfile_ros2-ardent
docker/Dockerfile_ros2-bouncy
docker/Dockerfile_ros2-crystal
docker/Dockerfile_ros2-dashing
docker/Dockerfile_ros2-eloquent
docker/Dockerfile_simulation-bionic
docker/Dockerfile_simulation-xenial

This is required in the MAVSDK Python test runner.

Add shutil via pip3

---

docker/Dockerfile_base-archlinux
docker/Dockerfile_base-bionic
docker/Dockerfile_base-xenial

docker: install psutil, not shutil

---

docker/Dockerfile_nuttx

px4-dev-nuttx: update arm-none-eabi-gcc to 9-2019-q4-major

---

docker/Dockerfile_base-archlinux
docker/Dockerfile_base-bionic
docker/Dockerfile_base-xenial
docker/Dockerfile_ros-kinetic
docker/Dockerfile_ros-melodic

Brings a minor dependency on the version checking which is useful on the microRTPS bridge code generation (https://github.com/PX4/Firmware/pull/14401).

pip: instal 'packaging'

---

docker/Dockerfile_clang
docker/Dockerfile_nuttx-bionic
docker/Dockerfile_nuttx-focal
docker/Dockerfile_nuttx_clang
docker/Dockerfile_raspi
docker/Dockerfile_ros-kinetic
docker/Dockerfile_ros-melodic
docker/Dockerfile_ros2-ardent
docker/Dockerfile_ros2-bouncy
docker/Dockerfile_ros2-crystal
docker/Dockerfile_ros2-dashing
docker/Dockerfile_ros2-eloquent
docker/Dockerfile_simulation-bionic
docker/Dockerfile_simulation-focal
docker/Dockerfile_simulation-xenial

To give continuity to https://github.com/PX4/Firmware/pull/14159.

update GNU Arm Embedded Toolchain to 9-2019-q4-major

---

docker/Dockerfile_armhf
docker/Dockerfile_base-archlinux
docker/Dockerfile_base-bionic
docker/Dockerfile_base-focal
docker/Dockerfile_base-xenial
docker/Dockerfile_ros-kinetic
docker/Dockerfile_ros-melodic
docker/Dockerfile_ros-noetic
docker/Dockerfile_ros2-ardent
docker/Dockerfile_ros2-bouncy
docker/Dockerfile_ros2-crystal
docker/Dockerfile_ros2-dashing
docker/Dockerfile_ros2-eloquent
docker/scripts/entrypoint.sh

* px4-dev-ros-kinetic: fix pip install
* px4-dev-ros2-bouncy: install Fast-RTPS 1.6.0 from source
* add and fix the entrypoint for ROS containers
* update Git repository name from FastRTPS to FastDDS
* px4-dev-base-focal: install FastRTPS 1.10.0

Various fixes to make the overall container set usable

---

.github/workflows/docker_builds.yml
docker/Makefile

This I think it's useful, so we are able to test the PR before merging.

CI: Run builds on PR's, only deploy on push

---

docker/Dockerfile_clang
docker/Dockerfile_nuttx-bionic
docker/Dockerfile_nuttx-focal
docker/Dockerfile_nuttx_clang
docker/Dockerfile_raspi
docker/Dockerfile_ros-kinetic
docker/Dockerfile_ros-melodic
docker/Dockerfile_ros-noetic
docker/Dockerfile_ros2-ardent
docker/Dockerfile_ros2-bouncy
docker/Dockerfile_ros2-crystal
docker/Dockerfile_ros2-dashing
docker/Dockerfile_ros2-eloquent
docker/Dockerfile_ros2-foxy
docker/Dockerfile_simulation-bionic
docker/Dockerfile_simulation-focal
docker/Dockerfile_simulation-xenial

JSBSim was added in #279 but this was causing build failures.
This reverts commit ae6c883dc83ccfce431a0012682debb0352c94ad.
Sorry to cause a mess.

Revert "Add JSBSim into simulation containers (#279)"

---

docker/Dockerfile_base-bionic
docker/Dockerfile_base-focal

Required for PX4/PX4-autopilot#14865 to fix CI

Add Nunavut to Ubuntu Bionic & Focal base docker

---

docker/Dockerfile_base-bionic
docker/Dockerfile_base-focal

Fixes CI build for https://github.com/PX4/PX4-Autopilot/pull/17100

Add Kconfiglib for Kconfig support

---

docker/Dockerfile_clang
docker/Dockerfile_nuttx-bionic
docker/Dockerfile_nuttx-focal
docker/Dockerfile_nuttx_clang
docker/Dockerfile_raspi
docker/Dockerfile_ros-kinetic
docker/Dockerfile_ros-melodic
docker/Dockerfile_ros-noetic
docker/Dockerfile_ros2-ardent
docker/Dockerfile_ros2-bouncy
docker/Dockerfile_ros2-crystal
docker/Dockerfile_ros2-dashing
docker/Dockerfile_ros2-eloquent
docker/Dockerfile_ros2-foxy
docker/Dockerfile_simulation-bionic
docker/Dockerfile_simulation-focal
docker/Dockerfile_simulation-xenial

@dagar Everything should be built now, except for Arch Linux which timed out due to some sourceforge ping issue.

Update tags (after nunavut update and rebuild)

---

docker/Dockerfile_clang
docker/Dockerfile_nuttx-bionic
docker/Dockerfile_nuttx-focal
docker/Dockerfile_nuttx_clang
docker/Dockerfile_raspi
docker/Dockerfile_ros-kinetic
docker/Dockerfile_ros-melodic
docker/Dockerfile_ros-noetic
docker/Dockerfile_ros2-ardent
docker/Dockerfile_ros2-bouncy
docker/Dockerfile_ros2-crystal
docker/Dockerfile_ros2-dashing
docker/Dockerfile_ros2-eloquent
docker/Dockerfile_ros2-foxy
docker/Dockerfile_simulation-bionic
docker/Dockerfile_simulation-focal
docker/Dockerfile_simulation-xenial

Everything seems to have built/pushed fine to dockerhub, so I've bumped the tags...

Update tags again

---

docker/Dockerfile_aarch64
docker/Dockerfile_armhf
docker/Dockerfile_base-archlinux
docker/Dockerfile_base-bionic
docker/Dockerfile_base-focal
docker/Dockerfile_base-xenial
docker/Dockerfile_ros-kinetic
docker/Dockerfile_ros-melodic

For https://github.com/PX4/PX4-Autopilot/pull/17479

pip: install jsonschema

---

docker/Dockerfile_ros-melodic
docker/Dockerfile_ros-noetic
docker/Dockerfile_ros2-dashing
docker/Dockerfile_ros2-eloquent
docker/Dockerfile_ros2-foxy
docker/Dockerfile_ros2-galactic
docker/Dockerfile_ros2-rolling

Following the [ROS GPG Key Expiration Incident](https://discourse.ros.org/t/ros-gpg-key-expiration-incident/20669).

ROS containers: update GPG keys

---

docker/Dockerfile_aarch64
docker/Dockerfile_armhf
docker/Dockerfile_base-archlinux

I've missed in #291 on some places to add the kconfiglib python module, this PR adds it to all targets.
Should fix https://github.com/PX4/PX4-Autopilot/pull/17100 CI

Add kconfiglib to all docker containers

---

docker/Dockerfile_clang
docker/Dockerfile_nuttx-bionic
docker/Dockerfile_nuttx-focal
docker/Dockerfile_nuttx_clang
docker/Dockerfile_raspi
docker/Dockerfile_ros-melodic
docker/Dockerfile_ros-noetic
docker/Dockerfile_ros2-dashing
docker/Dockerfile_ros2-eloquent
docker/Dockerfile_ros2-foxy
docker/Dockerfile_ros2-galactic
docker/Dockerfile_ros2-rolling
docker/Dockerfile_simulation-bionic
docker/Dockerfile_simulation-focal

Not sure how to create the tag itself

bump base container tag to 2021-08-18

---

README.md

was broken from rename of project

README: Update build badge
